--------------------------------------------------------
--  File creato - martedì-settembre-08-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONFIGURATION_FILES
--------------------------------------------------------

  CREATE TABLE "CONV"."CONFIGURATION_FILES" 
   (	"FILE_NAME" VARCHAR2(100 BYTE), 
	"FILE_ROW" NUMBER(*,0), 
	"LINE_CONTENT" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CONV"."CONFIGURATION_FILES"."FILE_NAME" IS 'NAME OF CONFIGURATION FILE';
   COMMENT ON COLUMN "CONV"."CONFIGURATION_FILES"."FILE_ROW" IS 'NUMBER OF ROW IN FILE';
   COMMENT ON COLUMN "CONV"."CONFIGURATION_FILES"."LINE_CONTENT" IS 'CONTENTO OF CURRENT ROW';
REM INSERTING into CONFIGURATION_FILES
SET DEFINE OFF;
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','0','<?xml version=''1.0''?>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','1','<xsl:stylesheet version="1.0"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','2','	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','3',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','4','	<xsl:output method="xml" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','5','	');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','6','	<xsl:template match="/">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','7','		<xsl:apply-templates select="RH" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','8','	</xsl:template>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','9',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','10','	<xsl:template match="RH">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','11','		<CBIDlyStmtReqLogMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','12','			<GrpHdr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','13','				<MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','14','					<xsl:value-of select="support_name" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','15','				</MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','16','				<CreDtTm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','17','					<xsl:value-of select="creation_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','18','				</CreDtTm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','19','				<MsgRcpt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','20','					<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','21','						<OrgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','22','							<Othr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','23','								<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','24','									<xsl:value-of select="recipient" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','25','								</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','26','							</Othr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','27','						</OrgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','28','					</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','29','				</MsgRcpt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','30','				<AddtlInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','31','					<xsl:value-of select="sender" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','32','				</AddtlInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','33','			</GrpHdr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','34','			<xsl:for-each select="x61">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','35','				<Stmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','36','					<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','37','						<xsl:value-of select="/RH/stmt_id" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','38','					</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','39','					<ElctrncSeqNb>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','40','						<xsl:value-of select="number" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','41','					</ElctrncSeqNb>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','42','					<CreDtTm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','43','						<xsl:value-of select="/RH/creation_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','44','					</CreDtTm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','45','					<CpyDplctInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','46','						<xsl:if test="reason = 93011">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','47','							DUPL');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','48','						</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','49','					</CpyDplctInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','50','					<Acct>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','51','						<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','52','							<IBAN>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','53','								<xsl:value-of select="iban" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','54','							</IBAN>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','55','						</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','56','						<Ccy>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','57','							<xsl:value-of select="currency_code" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','58','						</Ccy>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','59','						<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','60','							<Prtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','61','								<xsl:value-of select="account_type" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','62','							</Prtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','63','						</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','64','						<Nm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','65','							<xsl:value-of select="description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','66','						</Nm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','67','						<Svcr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','68','							<FinInstnId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','69','								<ClrSysMmbId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','70','									<MmbId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','71','										<xsl:value-of select="abi" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','72','									</MmbId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','73','								</ClrSysMmbId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','74','							</FinInstnId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','75','						</Svcr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','76','					</Acct>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','77',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','78','					<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','79','						<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','80','							<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','81','								<Cd>OPBD</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','82','							</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','83','						</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','84','						<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','85','							<xsl:value-of select="opening_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','86','						</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','87','						<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','88','							<xsl:if test="sign = C or sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','89','								CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','90','							</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','91','							<xsl:if test="sign = D or sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','92','								DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','93','							</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','94','						</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','95','						<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','96','							<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','97','								<xsl:value-of select="accounting_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','98','							</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','99','						</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','100','					</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','101','					<xsl:if test="x64">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','102','						<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','103','							<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','104','								<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','105','									<Cd>CLBD</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','106','								</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','107','							</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','108','							<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','109','								<xsl:value-of select="x64/accounts_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','110','							</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','111','							<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','112','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','113','									test="x64/accounts_balance_sign = C or x64/accounts_balance_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','114','									CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','115','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','116','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','117','									test="x64/accounts_balance_sign = D or x64/accounts_balance_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','118','									DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','119','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','120','							</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','121','							<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','122','								<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','123','									<xsl:value-of select="x64/accounting_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','124','								</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','125','							</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','126','						</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','127','						<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','128','							<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','129','								<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','130','									<Cd>CLAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','131','								</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','132','							</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','133','							<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','134','								<xsl:value-of select="x64/cash_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','135','							</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','136','							<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','137','								<xsl:if test="x64/cash_balance_sign = C or x64/cash_balance_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','138','									CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','139','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','140','								<xsl:if test="x64/cash_balance_sign = D or x64/cash_balance_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','141','									DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','142','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','143','							</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','144','							<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','145','								<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','146','									<xsl:value-of select="x64/accounting_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','147','								</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','148','							</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','149','						</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','150',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','151','					</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','152','					<xsl:if test="x65">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','153','						<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','154','							<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','155','								<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','156','									<Cd>FWAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','157','								</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','158','							</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','159','							<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','160','								<xsl:value-of select="x65/first_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','161','							</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','162','							<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','163','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','164','									test="x65/first_cash_on_hand_sign = C or x65/first_cash_on_hand_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','165','									CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','166','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','167','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','168','									test="x65/first_cash_on_hand_sign = D or x65/first_cash_on_hand_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','169','									DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','170','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','171','							</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','172','							<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','173','								<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','174','									<xsl:value-of select="x65/first_cash_on_hand_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','175','								</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','176','							</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','177','						</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','178','						<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','179','							<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','180','								<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','181','									<Cd>FWAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','182','								</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','183','							</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','184','							<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','185','								<xsl:value-of select="x65/second_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','186','							</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','187','							<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','188','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','189','									test="x65/second_cash_on_hand_sign = C or x65/second_cash_on_hand_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','190','									CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','191','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','192','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','193','									test="x65/second_cash_on_hand_sign = D or x65/second_cash_on_hand_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','194','									DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','195','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','196','							</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','197','							<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','198','								<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','199','									<xsl:value-of select="x65/second_cash_on_hand_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','200','								</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','201','							</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','202','						</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','203','						<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','204','							<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','205','								<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','206','									<Cd>FWAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','207','								</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','208','							</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','209','							<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','210','								<xsl:value-of select="x65/third_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','211','							</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','212','							<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','213','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','214','									test="x65/third_cash_on_hand_sign = C or x65/third_cash_on_hand_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','215','									CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','216','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','217','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','218','									test="x65/third_cash_on_hand_sign = D or x65/third_cash_on_hand_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','219','									DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','220','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','221','							</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','222','							<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','223','								<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','224','									<xsl:value-of select="x65/third_cash_on_hand_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','225','								</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','226','							</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','227','						</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','228','						<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','229','							<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','230','								<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','231','									<Cd>FWAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','232','								</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','233','							</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','234','							<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','235','								<xsl:value-of select="x65/fourth_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','236','							</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','237','							<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','238','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','239','									test="x65/fourth_cash_on_hand_sign = C or x65/fourth_cash_on_hand_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','240','									CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','241','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','242','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','243','									test="x65/fourth_cash_on_hand_sign = D or x65/fourth_cash_on_hand_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','244','									DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','245','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','246','							</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','247','							<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','248','								<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','249','									<xsl:value-of select="x65/fourth_cash_on_hand_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','250','								</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','251','							</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','252','						</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','253','						<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','254','							<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','255','								<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','256','									<Cd>FWAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','257','								</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','258','							</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','259','							<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','260','								<xsl:value-of select="x65/fifth_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','261','							</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','262','							<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','263','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','264','									test="x65/fifth_cash_on_hand_sign = C or x65/fifth_cash_on_hand_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','265','									CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','266','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','267','								<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','268','									test="x65/fifth_cash_on_hand_sign = D or x65/fifth_cash_on_hand_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','269','									DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','270','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','271','							</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','272','							<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','273','								<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','274','									<xsl:value-of select="x65/fifth_cash_on_hand_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','275','								</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','276','							</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','277','						</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','278','					</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','279',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','280',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','281','					<TxsSummry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','282','						<TtlNtries>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','283','							<NbOfNtries>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','284','								<xsl:value-of select="count(x62)" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','285','							</NbOfNtries>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','286','						</TtlNtries>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','287','					</TxsSummry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','288','					<xsl:for-each select="x62">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','289','						<Ntry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','290','							<NtryRef>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','291','								<xsl:value-of select="number" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','292','							</NtryRef>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','293','							<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','294','								<xsl:value-of select="amount" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','295','							</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','296','							<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','297','								<xsl:if test="sign = C or sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','298','									CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','299','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','300','								<xsl:if test="sign = D or sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','301','									DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','302','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','303','							</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','304','							<Sts>BOOK</Sts>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','305','							<BookgDt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','306','								<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','307','									<xsl:value-of select="account_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','308','								</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','309','							</BookgDt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','310','							<ValDt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','311','								<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','312','									<xsl:value-of select="date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','313','								</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','314','							</ValDt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','315','							<AcctSvcrRef>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','316','								<xsl:value-of select="bank_reference" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','317','							</AcctSvcrRef>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','318','							<BkTxCd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','319','								<Prtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','320','									<Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','321','										<xsl:value-of select="reason_internal_reason" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','322','									</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','323','								</Prtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','324','							</BkTxCd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','325','							<xsl:if test="x63[@structure_flag=''ZZ1'']">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','326','								<AmtDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','327','									<InstdAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','328','										<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','329','											<xsl:attribute name="ccy"><xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','330','												select="x63[@structure_flag=''ZZ1'']/currency_code" /></xsl:attribute>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','331','											<xsl:value-of select="x63[@structure_flag=''ZZ1'']/amount" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','332','										</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','333','									</InstdAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','334','									<TxAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','335','										<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','336','											<xsl:attribute name="ccy"><xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','337','												select="x63[@structure_flag=''ZZ1'']/currency_code_paid" /></xsl:attribute>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','338','											<xsl:value-of select="x63[@structure_flag=''ZZ1'']/paid" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','339','										</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','340','										<CcyXchg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','341','											<xchgRate>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','342','												<xsl:value-of select="x63[@structure_flag=''ZZ1'']/exchange_rate" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','343','											</xchgRate>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','344','										</CcyXchg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','345','									</TxAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','346','									<CntrValAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','347','										<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','348','											<xsl:attribute name="ccy"><xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','349','												select="x63[@structure_flag=''ZZ1'']/currency_code_transacted" /></xsl:attribute>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','350','											<xsl:value-of select="x63[@structure_flag=''ZZ1'']/transacted" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','351','										</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','352','									</CntrValAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','353','								</AmtDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','354','							</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','355','							<NtryDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','356','								<Btch>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','357','									<MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','358','										<xsl:value-of select="x63[@structure_flag=''ID1'']/msg_id" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','359','									</MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','360','									<PmtInfId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','361','										<xsl:value-of select="customer_movement_description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','362','									</PmtInfId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','363',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','364','								</Btch>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','365','								<TxDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','366','									<Refs>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','367','										<MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','368','											<xsl:value-of select="x63[@structure_flag=''ID1'']/msg_id" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','369','										</MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','370','										<PmtInfId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','371','											<xsl:value-of select="customer_movement_description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','372','										</PmtInfId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','373','										<EndToEndId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','374','											<xsl:value-of select="x63[@structure_flag=''ID1'']/end_to_end_id" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','375','										</EndToEndId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','376','										<ChqNb>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','377','											<xsl:value-of select="cheque_number" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','378','										</ChqNb>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','379',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','380','									</Refs>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','381','									<RltdPties>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','382','										<InitgPty>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','383','											<Nm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','384','												<xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','385','													select="x63[@structure_flag=''YYY'']/ordering_description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','386','												<xsl:value-of select="x63[@structure_flag=''ZZ2'']/ordering_party" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','387','											</Nm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','388','											<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','389','												<OrgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','390','													<Othr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','391','														<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','392','															<xsl:value-of select="x63[@structure_flag=''YYY'']/ordering_code" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','393','														</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','394','													</Othr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','395','												</OrgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','396','											</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','397','										</InitgPty>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','398','										<Cdtr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','399','											<xsl:value-of select="x63[@structure_flag=''ZZ3'']/payee" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','400','										</Cdtr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','401',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','402','									</RltdPties>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','403','									<RmtInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','404','										<Ustrd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','405','											<xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','406','												select="x63[@structure_flag=''RI1'']/reconciliation_data" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','407','											<xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','408','												select="x63[@structure_flag=''RI2'']/reconciliation_data" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','409','										</Ustrd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','410','									</RmtInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','411','									<RtrInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','412','										<AddtlInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','413','											<xsl:value-of select="x63[@structure_flag=''ZZ3'']/payment_reason" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','414','											<xsl:value-of select="x63[not(@structure_flag)]/description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','415','										</AddtlInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','416','									</RtrInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','417','								</TxDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','418','							</NtryDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','419','						</Ntry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','420','					</xsl:for-each>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','421','				</Stmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','422','			</xsl:for-each>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','423','		</CBIDlyStmtReqLogMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','424','	</xsl:template>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','425','</xsl:stylesheet>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','113','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','114','		<property name="names" value="type, content" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','115','		<property name="columns" value="2-3, 4-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','116','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','117','	<bean id="line62Tokenizer" class="com.xmlconverter.utils.FixedLengthTokenizerAggregator">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','118','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','119','			value="type, balance_number, number, date, account_date, sign, amount, reason, internal_reason, cheque_number, bank_reference, customer_reference_type, customer_movement_description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','120','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','121','			value="2-3, 4-10, 11-13, 14-19, 20-25, 26-26, 27-41, 42-43, 44-45, 46-61, 62-77, 78-86, 87-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','122','		<property name="aggregateFields">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','123','			<util:map id="aggregateFields">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','124','				<entry key="reason_internal_reason" value="reason, internal_reason" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','125','			</util:map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','126','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','127','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','128','	<bean id="line61Tokenizer" class="com.xmlconverter.utils.FixedLengthTokenizerAggregator">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','129','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','130','			value="type, number, filler1, original_abi, reason, description, account_type, cin, abi, cab, account_code, currency_code, accounting_date, sign, opening_balance, country_code, check_digit, filler2" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','131','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','132','			value="2-3, 4-10, 11-23, 24-28, 29-33, 34-49, 50-51, 52-52, 53-57, 58-62, 63-74, 75-77, 78-83, 84-84, 85-99, 100-101, 102-103, 104-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','133','		<property name="aggregateFields">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','134','			<util:map id="aggregateFields">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','135','				<entry key="iban"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','136','					value="country_code, check_digit, cin, abi, cab, account_code" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','137','			</util:map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','138','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','139','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','140','	<bean id="line63TokenizerKKK"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','141','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','142','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','143','			value="type, number, movement_number, structure_flag, type_identifier, filler" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','144','		<property name="columns" value="2-3, 4-10, 11-13, 14-16, 17-39, 40-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','145','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','146',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','147','	<bean id="line63Tokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','148','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','149','		<property name="names" value="type, number, movement_number, description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','150','		<property name="columns" value="2-3, 4-10, 11-13, 14-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','151','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','152',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','153','	<bean id="line63TokenizerYYY"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','154','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','155','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','156','			value="type, number, movement_number, structure_flag, order_date, ordering_code, ordering_description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','157','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','158','			value="2-3, 4-10, 11-13, 14-16, 17-24, 25-40, 41-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','159','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','160','	<bean id="line63TokenizerZZ1"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','161','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','162','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','163','			value="type, number, movement_number, structure_flag, amount, currency_code, paid, currency_code_paid, transacted, currency_code_transacted, exchange_rate, commission_amount, commission_fees, filler" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','164','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','165','			value="2-3, 4-10, 11-13, 14-16, 17-34, 35-37, 38-55, 56-58, 59-76, 77-79, 80-91, 92-104, 105-117, 118-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','166','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','167',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','168','	<bean id="line63TokenizerZZ2"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','169','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','170','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','171','			value="type, number, movement_number, structure_flag, ordering_party" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','172','		<property name="columns" value="2-3, 4-10, 11-13, 14-16, 17-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','173','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','174',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','175','	<bean id="line63TokenizerZZ3"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','176','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','177','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','178','			value="type, number, movement_number, structure_flag, payee, payment_reason" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','179','		<property name="columns" value="2-3, 4-10, 11-13, 14-16, 17-66, 67-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','180','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','181',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','182','	<bean id="line63TokenizerID1"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','183','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','184','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','185','			value="type, number, movement_number, structure_flag, msg_id, end_to_end_id, filler" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','186','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','187','			value="2-3, 4-10, 11-13, 14-16, 17-51, 52-86, 87-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','188','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','189',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','190','	<bean id="line63TokenizerRI1"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','191','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','192','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','193','			value="type, number, movement_number, structure_flag, reconciliation_data" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','194','		<property name="columns" value="2-3, 4-10, 11-13, 14-16, 17-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','195','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','196',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','197','	<bean id="line63TokenizerRI2"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','198','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','199','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','200','			value="type, number, movement_number, structure_flag, reconciliation_data, filler" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','201','		<property name="columns" value="2-3, 4-10, 11-13, 14-16, 17-52, 53-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','202','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','203',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','204','	<bean id="line64Tokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','205','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','0','<?xml version="1.0" encoding="UTF-8"?>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','1','<beans xmlns="http://www.springframework.org/schema/beans"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','2','	xmlns:batch="http://www.springframework.org/schema/batch" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','3','	xmlns:util="http://www.springframework.org/schema/util" xmlns:oxm="http://www.springframework.org/schema/oxm"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','4','	xsi:schemaLocation="http://www.springframework.org/schema/batch ');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','5','		http://www.springframework.org/schema/batch/spring-batch-2.2.xsd');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','6','		http://www.springframework.org/schema/beans ');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','7','		http://www.springframework.org/schema/beans/spring-beans-3.2.xsd');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','8','		http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','9','		http://www.springframework.org/schema/oxm http://www.springframework.org/schema/oxm/spring-oxm-1.5.xsd');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','10','		">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','11',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','12',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','13','	<bean id="outputResource" class="org.springframework.core.io.FileSystemResource">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','14','		<!-- constructor-arg value="csv/outputs/domain.all._external3.xml" / -->');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','15','		<constructor-arg value="${output_file}" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','16','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','17',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','18','	<bean id="itemWriter" class="org.springframework.batch.item.file.FlatFileItemWriter">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','19','		<property name="resource" ref="outputResource" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','20','		<property name="lineAggregator">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','21','			<bean');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','22','				class="org.springframework.batch.item.file.transform.PassThroughLineAggregator" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','23','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','24','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','25',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','26','	<!-- START job RH -->');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','27','	<bean id="job_listener" class="com.xmlconverter.utils.JobListener_setup" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','28','	<job id="readMultiLineJobRH" xmlns="http://www.springframework.org/schema/batch">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','29',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','30','		<step id="stepRH">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','31','			<tasklet>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','32','				<chunk reader="multiLineReader" writer="itemWriter" processor="RHProcessor2"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','33','					commit-interval="1" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','34','			</tasklet>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','35','		</step>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','36','		<listeners>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','37','			<listener ref="job_listener" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','38',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','39','		</listeners>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','40','	</job>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','41',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','42',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','43','	<bean id="RHProcessor2" class="com.xmlconverter.CBI_RH_Processor2">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','44','		<property name="template" ref="template_xslt" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','45','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','46','	<bean id="template_xslt" class="com.xmlconverter.XSLT_Templates">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','47','		<constructor-arg value="${xslt_file}" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','48','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','49',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','50',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','51','	<bean id="multiLineReader" class="com.xmlconverter.CBI_RH_MultiLineItemReader2">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','52','		<property name="header" value="RH" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','53','		<property name="footer" value="EF" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','54','		<property name="keyToPath">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','55','			<map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','56','				<entry key="61" value="//RH" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','57','				<entry key="62" value="//RH/x61[last()]" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','58','				<entry key="63" value="//RH/x61[last()]/x62[last()]" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','59','				<entry key="64" value="//RH/x61[last()]" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','60','				<entry key="65" value="//RH/x61[last()]" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','61',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','62','			</map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','63','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','64','		<property name="delegate">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','65','			<bean class="org.springframework.batch.item.file.FlatFileItemReader">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','66','				<property name="resource" value="file:${input_file}" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','67','				<property name="lineMapper">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','68','					<bean');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','69','						class="org.springframework.batch.item.file.mapping.DefaultLineMapper">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','70','						<property name="lineTokenizer" ref="RHFileTokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','71','						<property name="fieldSetMapper">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','72','							<bean');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','73','								class="org.springframework.batch.item.file.mapping.PassThroughFieldSetMapper" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','74','						</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','75','					</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','76','				</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','77','			</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','78','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','79','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','80',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','81','	<bean id="RHFileTokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','82','		class="org.springframework.batch.item.file.transform.PatternMatchingCompositeLineTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','83','		<property name="tokenizers">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','84','			<map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','85','				<entry key=" RH*" value-ref="headerRHTokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','86','				<entry key=" EF*" value-ref="footerRHTokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','87','				<entry key=" 62*" value-ref="line62Tokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','88','				<entry key=" 61*" value-ref="line61Tokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','89',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','90','				<entry key=" 63??????????KKK*" value-ref="line63TokenizerKKK" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','91','				<entry key=" 63??????????YYY*" value-ref="line63TokenizerYYY" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','92','				<entry key=" 63??????????ZZ1*" value-ref="line63TokenizerZZ1" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','93','				<entry key=" 63??????????ZZ2*" value-ref="line63TokenizerZZ2" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','94','				<entry key=" 63??????????ZZ3*" value-ref="line63TokenizerZZ3" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','95','				<entry key=" 63??????????ID1*" value-ref="line63TokenizerID1" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','96','				<entry key=" 63??????????RI1*" value-ref="line63TokenizerRI1" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','97','				<entry key=" 63??????????RI2*" value-ref="line63TokenizerRI2" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','98','				<entry key=" 63*" value-ref="line63Tokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','99',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','100','				<entry key=" 64*" value-ref="line64Tokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','101','				<entry key=" 65*" value-ref="line65Tokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','102','			</map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','103','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','104','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','105',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','106','	<bean id="headerRHTokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','107','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','108','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','109','			value="type, sender, recipient, creation_date, support_name, filler, stmt_id" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','110','		<property name="columns" value="2-3, 4-8, 9-13, 14-19, 20-39, 40-120, 2-39" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','111','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','112','	<bean id="footerRHTokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','206','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','207','			value="type, number, currency_code, accounting_date, accounts_balance_sign, accounts_balance, cash_balance_sign, cash_balance, filler1, filler2" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','208','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','209','			value="2-3, 4-10, 11-13, 14-19, 20-20, 21-35, 36-36, 37-51, 52-105, 106-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','210','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','211',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','212','	<bean id="line65Tokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','213','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','214','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','215','			value="type, number, first_cash_balance, first_cash_on_hand_date, first_cash_on_hand_sign, first_cash_on_hand_balance, second_cash_balance, second_cash_on_hand_date, second_cash_on_hand_sign, second_cash_on_hand_balance, third_cash_balance, third_cash_on_hand_date, third_cash_on_hand_sign, third_cash_on_hand_balance, fourth_cash_balance, fourth_cash_on_hand_date, fourth_cash_on_hand_sign, fourth_cash_on_hand_balance, ');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','216','			fifth_cash_balance, fifth_cash_on_hand_date, fifth_cash_on_hand_sign, fifth_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','217','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','218','			value="2-3, 4-10, 11-32, 11-16, 17-17, 18-32, 33-54, 33-38, 39-39, 40-54, 55-76, 55-60, 61-61, 62-76, 77-98, 77-82, 83-83, 84-98, 99-120, 99-104, 105-105, 106-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','219','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','220',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','221','</beans>');
--------------------------------------------------------
--  DDL for Index CONFIGURATION_FILES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONV"."CONFIGURATION_FILES_PK" ON "CONV"."CONFIGURATION_FILES" ("FILE_NAME", "FILE_ROW") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CONFIGURATION_FILES
--------------------------------------------------------

  ALTER TABLE "CONV"."CONFIGURATION_FILES" ADD CONSTRAINT "CONFIGURATION_FILES_PK" PRIMARY KEY ("FILE_NAME", "FILE_ROW")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONV"."CONFIGURATION_FILES" MODIFY ("FILE_ROW" NOT NULL ENABLE);
  ALTER TABLE "CONV"."CONFIGURATION_FILES" MODIFY ("FILE_NAME" NOT NULL ENABLE);
