--------------------------------------------------------
--  File creato - giovedì-settembre-10-2015   
--------------------------------------------------------
REM INSERTING into CONFIGURATION_FILES
SET DEFINE OFF;
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','261','										</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','262','									</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','263','									<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','264','										<xsl:value-of select="x65/fifth_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','265','									</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','266','									<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','267','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','268','											test="x65/fifth_cash_on_hand_sign = C or x65/fifth_cash_on_hand_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','269','											CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','270','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','271','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','272','											test="x65/fifth_cash_on_hand_sign = D or x65/fifth_cash_on_hand_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','273','											DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','274','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','275','									</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','276','									<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','277','										<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','278','											<xsl:value-of select="x65/fifth_cash_on_hand_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','279','										</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','280','									</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','281','								</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','282','							</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','283',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','284',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','285','							<TxsSummry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','286','								<TtlNtries>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','287','									<NbOfNtries>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','288','										<xsl:value-of select="count(x62)" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','289','									</NbOfNtries>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','290','								</TtlNtries>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','291','							</TxsSummry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','292','							<xsl:for-each select="x62">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','293','								<Ntry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','294','									<NtryRef>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','295','										<xsl:value-of select="number" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','296','									</NtryRef>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','297','									<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','298','										<xsl:value-of select="amount" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','299','									</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','300','									<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','301','										<xsl:if test="sign = C or sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','302','											CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','303','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','304','										<xsl:if test="sign = D or sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','305','											DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','306','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','307','									</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','308','									<Sts>BOOK</Sts>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','309','									<BookgDt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','310','										<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','311','											<xsl:value-of select="account_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','312','										</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','313','									</BookgDt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','314','									<ValDt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','315','										<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','316','											<xsl:value-of select="date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','317','										</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','318','									</ValDt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','319','									<AcctSvcrRef>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','320','										<xsl:value-of select="bank_reference" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','321','									</AcctSvcrRef>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','322','									<BkTxCd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','323','										<Prtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','324','											<Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','325','												<xsl:value-of select="reason_internal_reason" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','326','											</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','327','										</Prtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','328','									</BkTxCd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','329','									<xsl:if test="x63[@structure_flag=''ZZ1'']">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','330','										<AmtDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','331','											<InstdAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','332','												<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','333','													<xsl:attribute name="ccy"><xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','334','														select="x63[@structure_flag=''ZZ1'']/currency_code" /></xsl:attribute>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','335','													<xsl:value-of select="x63[@structure_flag=''ZZ1'']/amount" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','336','												</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','337','											</InstdAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','338','											<TxAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','339','												<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','340','													<xsl:attribute name="ccy"><xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','341','														select="x63[@structure_flag=''ZZ1'']/currency_code_paid" /></xsl:attribute>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','342','													<xsl:value-of select="x63[@structure_flag=''ZZ1'']/paid" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','343','												</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','344','												<CcyXchg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','345','													<xchgRate>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','346','														<xsl:value-of select="x63[@structure_flag=''ZZ1'']/exchange_rate" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','347','													</xchgRate>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','348','												</CcyXchg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','349','											</TxAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','350','											<CntrValAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','351','												<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','352','													<xsl:attribute name="ccy"><xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','353','														select="x63[@structure_flag=''ZZ1'']/currency_code_transacted" /></xsl:attribute>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','354','													<xsl:value-of select="x63[@structure_flag=''ZZ1'']/transacted" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','355','												</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','356','											</CntrValAmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','357','										</AmtDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','358','									</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','359','									<NtryDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','360','										<Btch>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','361','											<MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','362','												<xsl:value-of select="x63[@structure_flag=''ID1'']/msg_id" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','363','											</MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','364','											<PmtInfId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','365','												<xsl:value-of select="customer_movement_description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','366','											</PmtInfId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','367',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','368','										</Btch>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','369','										<TxDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','370','											<Refs>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','371','												<MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','372','													<xsl:value-of select="x63[@structure_flag=''ID1'']/msg_id" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','373','												</MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','374','												<PmtInfId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','375','													<xsl:value-of select="customer_movement_description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','376','												</PmtInfId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','377','												<EndToEndId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','136','										<xsl:value-of select="x64/cash_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','137','									</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','138','									<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','139','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','140','											test="x64/cash_balance_sign = C or x64/cash_balance_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','141','											CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','142','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','143','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','144','											test="x64/cash_balance_sign = D or x64/cash_balance_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','145','											DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','146','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','147','									</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','148','									<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','149','										<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','150','											<xsl:value-of select="x64/accounting_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','151','										</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','152','									</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','153','								</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','154',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','155','							</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','156','							<xsl:if test="x65">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','157','								<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','158','									<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','159','										<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','160','											<Cd>FWAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','161','										</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','162','									</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','163','									<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','164','										<xsl:value-of select="x65/first_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','165','									</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','166','									<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','167','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','168','											test="x65/first_cash_on_hand_sign = C or x65/first_cash_on_hand_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','169','											CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','170','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','171','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','172','											test="x65/first_cash_on_hand_sign = D or x65/first_cash_on_hand_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','173','											DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','174','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','175','									</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','176','									<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','177','										<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','178','											<xsl:value-of select="x65/first_cash_on_hand_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','179','										</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','180','									</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','181','								</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','182','								<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','183','									<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','184','										<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','185','											<Cd>FWAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','186','										</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','187','									</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','188','									<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','189','										<xsl:value-of select="x65/second_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','190','									</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','191','									<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','192','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','193','											test="x65/second_cash_on_hand_sign = C or x65/second_cash_on_hand_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','194','											CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','195','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','196','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','197','											test="x65/second_cash_on_hand_sign = D or x65/second_cash_on_hand_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','198','											DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','199','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','200','									</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','201','									<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','202','										<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','203','											<xsl:value-of select="x65/second_cash_on_hand_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','204','										</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','205','									</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','206','								</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','207','								<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','208','									<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','209','										<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','210','											<Cd>FWAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','211','										</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','212','									</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','213','									<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','214','										<xsl:value-of select="x65/third_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','215','									</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','216','									<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','217','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','218','											test="x65/third_cash_on_hand_sign = C or x65/third_cash_on_hand_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','219','											CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','220','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','221','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','222','											test="x65/third_cash_on_hand_sign = D or x65/third_cash_on_hand_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','223','											DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','224','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','225','									</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','226','									<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','227','										<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','228','											<xsl:value-of select="x65/third_cash_on_hand_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','229','										</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','230','									</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','231','								</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','232','								<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','233','									<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','234','										<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','235','											<Cd>FWAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','236','										</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','237','									</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','238','									<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','239','										<xsl:value-of select="x65/fourth_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','240','									</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','241','									<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','242','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','243','											test="x65/fourth_cash_on_hand_sign = C or x65/fourth_cash_on_hand_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','244','											CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','245','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','246','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','247','											test="x65/fourth_cash_on_hand_sign = D or x65/fourth_cash_on_hand_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','248','											DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','249','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','250','									</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','251','									<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','252','										<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','253','											<xsl:value-of select="x65/fourth_cash_on_hand_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','254','										</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','255','									</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','256','								</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','257','								<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','258','									<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','259','										<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','260','											<Cd>FWAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','0','<?xml version=''1.0''?>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','1','<xsl:stylesheet version="1.0"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','2','	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','3',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','4','	<xsl:output method="xml" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','5',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','6','	<xsl:template match="/">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','7','		<xsl:apply-templates select="RH" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','8','	</xsl:template>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','9',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','10','	<xsl:template match="RH">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','11','		<CBIEnvelBkToCstmrStmtReqLogMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','12','			<CBIBkToCstmrStmtReqLogMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','13','				<CBIDlyStmtReqLogMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','14','					<GrpHdr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','15','						<MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','16','							<xsl:value-of select="support_name" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','17','						</MsgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','18','						<CreDtTm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','19','							<xsl:value-of select="creation_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','20','						</CreDtTm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','21','						<MsgRcpt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','22','							<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','23','								<OrgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','24','									<Othr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','25','										<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','26','											<xsl:value-of select="recipient" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','27','										</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','28','									</Othr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','29','								</OrgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','30','							</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','31','						</MsgRcpt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','32','						<AddtlInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','33','							<xsl:value-of select="sender" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','34','						</AddtlInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','35','					</GrpHdr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','36','					<xsl:for-each select="x61">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','37','						<Stmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','38','							<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','39','								<xsl:value-of select="/RH/stmt_id" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','40','							</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','41','							<ElctrncSeqNb>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','42','								<xsl:value-of select="number" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','43','							</ElctrncSeqNb>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','44','							<CreDtTm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','45','								<xsl:value-of select="/RH/creation_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','46','							</CreDtTm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','47','							<CpyDplctInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','48','								<xsl:if test="reason = 93011">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','49','									DUPL');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','50','								</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','51','							</CpyDplctInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','52','							<Acct>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','53','								<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','54','									<IBAN>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','55','										<xsl:value-of select="iban" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','56','									</IBAN>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','57','								</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','58','								<Ccy>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','59','									<xsl:value-of select="currency_code" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','60','								</Ccy>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','61','								<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','62','									<Prtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','63','										<xsl:value-of select="account_type" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','64','									</Prtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','65','								</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','66','								<Nm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','67','									<xsl:value-of select="description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','68','								</Nm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','69','								<Svcr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','70','									<FinInstnId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','71','										<ClrSysMmbId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','72','											<MmbId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','73','												<xsl:value-of select="abi" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','74','											</MmbId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','75','										</ClrSysMmbId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','76','									</FinInstnId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','77','								</Svcr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','78','							</Acct>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','79',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','80','							<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','81','								<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','82','									<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','83','										<Cd>OPBD</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','84','									</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','85','								</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','86','								<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','87','									<xsl:value-of select="opening_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','88','								</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','89','								<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','90','									<xsl:if test="sign = C or sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','91','										CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','92','									</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','93','									<xsl:if test="sign = D or sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','94','										DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','95','									</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','96','								</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','97','								<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','98','									<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','99','										<xsl:value-of select="accounting_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','100','									</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','101','								</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','102','							</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','103','							<xsl:if test="x64">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','104','								<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','105','									<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','106','										<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','107','											<Cd>CLBD</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','108','										</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','109','									</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','110','									<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','111','										<xsl:value-of select="x64/accounts_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','112','									</Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','113','									<CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','114','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','115','											test="x64/accounts_balance_sign = C or x64/accounts_balance_sign = c">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','116','											CRDT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','117','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','118','										<xsl:if');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','119','											test="x64/accounts_balance_sign = D or x64/accounts_balance_sign = d">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','120','											DBIT');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','121','										</xsl:if>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','122','									</CdtDbtInd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','123','									<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','124','										<Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','125','											<xsl:value-of select="x64/accounting_date" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','126','										</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','127','									</Dt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','128','								</Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','129','								<Bal>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','130','									<Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','131','										<CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','132','											<Cd>CLAV</Cd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','133','										</CdOrPrtry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','134','									</Tp>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','135','									<Amt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','114','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','115','			value="type, sender, recipient, creation_date, support_name, filler, stmt_id" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','116','		<property name="columns" value="2-3, 4-8, 9-13, 14-19, 20-39, 40-120, 2-39" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','117','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','118','	<bean id="footerRHTokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','119','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','120','		<property name="names" value="type, content" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','121','		<property name="columns" value="2-3, 4-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','122','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','123','	<bean id="line62Tokenizer" class="com.xmlconverter.utils.FixedLengthTokenizerAggregator">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','124','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','125','			value="type, balance_number, number, date, account_date, sign, amount, reason, internal_reason, cheque_number, bank_reference, customer_reference_type, customer_movement_description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','126','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','127','			value="2-3, 4-10, 11-13, 14-19, 20-25, 26-26, 27-41, 42-43, 44-45, 46-61, 62-77, 78-86, 87-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','128','		<property name="aggregateFields">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','129','			<util:map id="aggregateFields">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','130','				<entry key="reason_internal_reason" value="reason, internal_reason" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','131','			</util:map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','132','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','133','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','134','	<bean id="line61Tokenizer" class="com.xmlconverter.utils.FixedLengthTokenizerAggregator">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','135','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','136','			value="type, number, filler1, original_abi, reason, description, account_type, cin, abi, cab, account_code, currency_code, accounting_date, sign, opening_balance, country_code, check_digit, filler2" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','137','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','138','			value="2-3, 4-10, 11-23, 24-28, 29-33, 34-49, 50-51, 52-52, 53-57, 58-62, 63-74, 75-77, 78-83, 84-84, 85-99, 100-101, 102-103, 104-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','139','		<property name="aggregateFields">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','140','			<util:map id="aggregateFields">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','141','				<entry key="iban"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','142','					value="country_code, check_digit, cin, abi, cab, account_code" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','143','			</util:map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','144','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','145','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','146','	<bean id="line63TokenizerKKK"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','147','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','148','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','149','			value="type, number, movement_number, structure_flag, type_identifier, filler" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','150','		<property name="columns" value="2-3, 4-10, 11-13, 14-16, 17-39, 40-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','151','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','152',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','153','	<bean id="line63Tokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','154','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','155','		<property name="names" value="type, number, movement_number, description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','156','		<property name="columns" value="2-3, 4-10, 11-13, 14-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','157','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','158',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','159','	<bean id="line63TokenizerYYY"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','160','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','161','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','162','			value="type, number, movement_number, structure_flag, order_date, ordering_code, ordering_description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','163','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','164','			value="2-3, 4-10, 11-13, 14-16, 17-24, 25-40, 41-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','165','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','166','	<bean id="line63TokenizerZZ1"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','167','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','168','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','169','			value="type, number, movement_number, structure_flag, amount, currency_code, paid, currency_code_paid, transacted, currency_code_transacted, exchange_rate, commission_amount, commission_fees, filler" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','170','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','171','			value="2-3, 4-10, 11-13, 14-16, 17-34, 35-37, 38-55, 56-58, 59-76, 77-79, 80-91, 92-104, 105-117, 118-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','172','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','173',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','174','	<bean id="line63TokenizerZZ2"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','175','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','176','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','177','			value="type, number, movement_number, structure_flag, ordering_party" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','178','		<property name="columns" value="2-3, 4-10, 11-13, 14-16, 17-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','179','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','180',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','181','	<bean id="line63TokenizerZZ3"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','182','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','183','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','184','			value="type, number, movement_number, structure_flag, payee, payment_reason" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','185','		<property name="columns" value="2-3, 4-10, 11-13, 14-16, 17-66, 67-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','186','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','187',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','188','	<bean id="line63TokenizerID1"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','189','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','190','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','191','			value="type, number, movement_number, structure_flag, msg_id, end_to_end_id, filler" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','192','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','193','			value="2-3, 4-10, 11-13, 14-16, 17-51, 52-86, 87-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','194','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','195',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','196','	<bean id="line63TokenizerRI1"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','197','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','198','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','199','			value="type, number, movement_number, structure_flag, reconciliation_data" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','200','		<property name="columns" value="2-3, 4-10, 11-13, 14-16, 17-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','201','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','202',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','203','	<bean id="line63TokenizerRI2"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','204','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','205','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','206','			value="type, number, movement_number, structure_flag, reconciliation_data, filler" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','207','		<property name="columns" value="2-3, 4-10, 11-13, 14-16, 17-52, 53-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','208','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','209',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','210','	<bean id="line64Tokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','0','<?xml version="1.0" encoding="UTF-8"?>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','1','<beans xmlns="http://www.springframework.org/schema/beans"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','2','	xmlns:batch="http://www.springframework.org/schema/batch" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','3','	xmlns:util="http://www.springframework.org/schema/util" xmlns:oxm="http://www.springframework.org/schema/oxm"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','4','	xsi:schemaLocation="http://www.springframework.org/schema/batch ');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','5','		http://www.springframework.org/schema/batch/spring-batch-2.2.xsd');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','6','		http://www.springframework.org/schema/beans ');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','7','		http://www.springframework.org/schema/beans/spring-beans-3.2.xsd');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','8','		http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','9','		http://www.springframework.org/schema/oxm http://www.springframework.org/schema/oxm/spring-oxm-1.5.xsd');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','10','		">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','11',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','12',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','13','	<bean id="outputResource" class="org.springframework.core.io.FileSystemResource">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','14','		<!-- constructor-arg value="csv/outputs/domain.all._external3.xml" / -->');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','15','		<constructor-arg value="${output_file}" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','16','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','17',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','18','	<bean id="itemWriter" class="org.springframework.batch.item.file.FlatFileItemWriter">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','19','		<property name="resource" ref="outputResource" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','20','		<property name="lineAggregator">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','21','			<bean');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','22','				class="org.springframework.batch.item.file.transform.PassThroughLineAggregator" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','23','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','24','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','25',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','26','	<!-- START job RH -->');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','27','	<bean id="job_listener" class="com.xmlconverter.utils.JobListener_setup" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','28','	<job id="readMultiLineJobRH" xmlns="http://www.springframework.org/schema/batch">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','29',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','30','		<step id="stepRH">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','31','			<tasklet>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','32','				<chunk reader="multiLineReader" writer="itemWriter" processor="RHProcessor2"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','33','					commit-interval="1" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','34','			</tasklet>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','35','		</step>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','36','		<listeners>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','37','			<listener ref="job_listener" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','38',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','39','		</listeners>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','40','	</job>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','41',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','42',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','43','	<bean id="RHProcessor2" class="com.xmlconverter.CBI_RH_Processor2">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','44','		<property name="template" ref="template_xslt" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','45','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','46','	<bean id="template_xslt" class="com.xmlconverter.XSLT_Templates">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','47','		<constructor-arg value="${xslt_file}" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','48','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','49',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','50',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','51','	<bean id="multiLineReader" class="com.xmlconverter.CBI_RH_MultiLineItemReader2">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','52','		<property name="header" value="RH" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','53','		<property name="footer" value="EF" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','54','		<property name="type_property" value="type" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','55','		<property name="attribute_property" value="structure_flag" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','56','		<property name="consecutive_join_property" value="description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','57','		');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','58','		<property name="x_tag_prefix" value="x" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','59','		');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','60','		<property name="keyToPath">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','61','			<map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','62','				<entry key="61" value="//RH" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','63','				<entry key="62" value="//RH/x61[last()]" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','64','				<entry key="63" value="//RH/x61[last()]/x62[last()]" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','65','				<entry key="64" value="//RH/x61[last()]" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','66','				<entry key="65" value="//RH/x61[last()]" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','67',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','68','			</map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','69','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','70','		<property name="delegate">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','71','			<bean class="org.springframework.batch.item.file.FlatFileItemReader">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','72','				<property name="resource" value="file:${input_file}" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','73','				<property name="lineMapper">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','74','					<bean');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','75','						class="org.springframework.batch.item.file.mapping.DefaultLineMapper">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','76','						<property name="lineTokenizer" ref="RHFileTokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','77','						<property name="fieldSetMapper">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','78','							<bean');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','79','								class="org.springframework.batch.item.file.mapping.PassThroughFieldSetMapper" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','80','						</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','81','					</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','82','				</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','83','			</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','84','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','85','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','86',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','87','	<bean id="RHFileTokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','88','		class="org.springframework.batch.item.file.transform.PatternMatchingCompositeLineTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','89','		<property name="tokenizers">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','90','			<map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','91','				<entry key=" RH*" value-ref="headerRHTokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','92','				<entry key=" EF*" value-ref="footerRHTokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','93','				<entry key=" 62*" value-ref="line62Tokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','94','				<entry key=" 61*" value-ref="line61Tokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','95',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','96','				<entry key=" 63??????????KKK*" value-ref="line63TokenizerKKK" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','97','				<entry key=" 63??????????YYY*" value-ref="line63TokenizerYYY" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','98','				<entry key=" 63??????????ZZ1*" value-ref="line63TokenizerZZ1" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','99','				<entry key=" 63??????????ZZ2*" value-ref="line63TokenizerZZ2" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','100','				<entry key=" 63??????????ZZ3*" value-ref="line63TokenizerZZ3" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','101','				<entry key=" 63??????????ID1*" value-ref="line63TokenizerID1" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','102','				<entry key=" 63??????????RI1*" value-ref="line63TokenizerRI1" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','103','				<entry key=" 63??????????RI2*" value-ref="line63TokenizerRI2" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','104','				<entry key=" 63*" value-ref="line63Tokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','105',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','106','				<entry key=" 64*" value-ref="line64Tokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','107','				<entry key=" 65*" value-ref="line65Tokenizer" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','108','			</map>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','109','		</property>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','110','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','111',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','112','	<bean id="headerRHTokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','113','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','0','<CBIBkToCstmrStmtReqPhyMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','1','	<CBIHdrTrt/>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','2','	<CBIHdrSrv/>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','3','	<CBIBdyBkToCstmrStmtReq>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','4','		<PhyMsgInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','5','			<PhyMsgTpCd/>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','6','			<NbOfLogMsg>X</NbOfLogMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','379','												</EndToEndId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','380','												<ChqNb>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','381','													<xsl:value-of select="cheque_number" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','382','												</ChqNb>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','383',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','384','											</Refs>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','385','											<RltdPties>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','386','												<InitgPty>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','387','													<Nm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','388','														<xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','389','															select="x63[@structure_flag=''YYY'']/ordering_description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','390','														<xsl:value-of select="x63[@structure_flag=''ZZ2'']/ordering_party" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','391','													</Nm>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','392','													<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','393','														<OrgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','394','															<Othr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','7','		</PhyMsgInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','8','		{{XMLmesg}}');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','9','		</CBIBdyBkToCstmrStmtReq>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('envelope.xml','10','</CBIBkToCstmrStmtReqPhyMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','395','																<Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','396','																	<xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','397','																		select="x63[@structure_flag=''YYY'']/ordering_code" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','398','																</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','399','															</Othr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','378','													<xsl:value-of select="x63[@structure_flag=''ID1'']/end_to_end_id" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','400','														</OrgId>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','401','													</Id>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','402','												</InitgPty>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','403','												<Cdtr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','404','													<xsl:value-of select="x63[@structure_flag=''ZZ3'']/payee" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','405','												</Cdtr>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','406',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','407','											</RltdPties>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','408','											<RmtInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','409','												<Ustrd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','410','													<xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','411','														select="x63[@structure_flag=''RI1'']/reconciliation_data" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','412','													<xsl:value-of');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','413','														select="x63[@structure_flag=''RI2'']/reconciliation_data" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','414','												</Ustrd>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','415','											</RmtInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','416','											<RtrInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','417','												<AddtlInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','418','													<xsl:value-of select="x63[@structure_flag=''ZZ3'']/payment_reason" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','419','													<xsl:value-of select="x63[not(@structure_flag)]/description" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','420','												</AddtlInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','421','											</RtrInf>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','422','										</TxDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','423','									</NtryDtls>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','424','								</Ntry>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','425','							</xsl:for-each>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','426','						</Stmt>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','427','					</xsl:for-each>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','428','				</CBIDlyStmtReqLogMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','429','			</CBIBkToCstmrStmtReqLogMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','430','		</CBIEnvelBkToCstmrStmtReqLogMsg>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','431','	</xsl:template>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('RH_transform.xslt','432','</xsl:stylesheet>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','211','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','212','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','213','			value="type, number, currency_code, accounting_date, accounts_balance_sign, accounts_balance, cash_balance_sign, cash_balance, filler1, filler2" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','214','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','215','			value="2-3, 4-10, 11-13, 14-19, 20-20, 21-35, 36-36, 37-51, 52-105, 106-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','216','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','217',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','218','	<bean id="line65Tokenizer"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','219','		class="org.springframework.batch.item.file.transform.FixedLengthTokenizer">');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','220','		<property name="names"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','221','			value="type, number, first_cash_balance, first_cash_on_hand_date, first_cash_on_hand_sign, first_cash_on_hand_balance, second_cash_balance, second_cash_on_hand_date, second_cash_on_hand_sign, second_cash_on_hand_balance, third_cash_balance, third_cash_on_hand_date, third_cash_on_hand_sign, third_cash_on_hand_balance, fourth_cash_balance, fourth_cash_on_hand_date, fourth_cash_on_hand_sign, fourth_cash_on_hand_balance, ');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','222','			fifth_cash_balance, fifth_cash_on_hand_date, fifth_cash_on_hand_sign, fifth_cash_on_hand_balance" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','223','		<property name="columns"');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','224','			value="2-3, 4-10, 11-32, 11-16, 17-17, 18-32, 33-54, 33-38, 39-39, 40-54, 55-76, 55-60, 61-61, 62-76, 77-98, 77-82, 83-83, 84-98, 99-120, 99-104, 105-105, 106-120" />');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','225','	</bean>');
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','226',null);
Insert into CONFIGURATION_FILES (FILE_NAME,FILE_ROW,LINE_CONTENT) values ('job-xslt.xml','227','</beans>');
