//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 06:46:19 PM CEST 
//


package com.trim.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CBIBalanceType12Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CBIBalanceType12Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CLAV"/>
 *     &lt;enumeration value="CLBD"/>
 *     &lt;enumeration value="FWAV"/>
 *     &lt;enumeration value="OPAV"/>
 *     &lt;enumeration value="OPBD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CBIBalanceType12Code")
@XmlEnum
public enum CBIBalanceType12Code {

    CLAV,
    CLBD,
    FWAV,
    OPAV,
    OPBD;

    public String value() {
        return name();
    }

    public static CBIBalanceType12Code fromValue(String v) {
        return valueOf(v);
    }

}
