//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 06:46:19 PM CEST 
//


package com.trim.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CBIDlyStmtReqLogMsg.00.01.02 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CBIDlyStmtReqLogMsg.00.01.02">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrpHdr" type="{urn:CBI:xsd:CBIDlyStmtReqLogMsg.00.01.02}CBIGroupHeader42"/>
 *         &lt;element name="Stmt" type="{urn:CBI:xsd:CBIDlyStmtReqLogMsg.00.01.02}CBIAccountStatement2_1" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CBIDlyStmtReqLogMsg.00.01.02", propOrder = {
    "grpHdr",
    "stmt"
})
public class CBIDlyStmtReqLogMsg000102 {

    @XmlElement(name = "GrpHdr", required = true)
    protected CBIGroupHeader42 grpHdr;
    @XmlElement(name = "Stmt", required = true)
    protected List<CBIAccountStatement21> stmt;

    /**
     * Gets the value of the grpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link CBIGroupHeader42 }
     *     
     */
    public CBIGroupHeader42 getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIGroupHeader42 }
     *     
     */
    public void setGrpHdr(CBIGroupHeader42 value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the stmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CBIAccountStatement21 }
     * 
     * 
     */
    public List<CBIAccountStatement21> getStmt() {
        if (stmt == null) {
            stmt = new ArrayList<CBIAccountStatement21>();
        }
        return this.stmt;
    }

}
