//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 10:18:42 PM CEST 
//


package com.trim.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.trim.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CBIDlyStmtReqLogMsg_QNAME = new QName("urn:CBI:xsd:CBIDlyStmtReqLogMsg.00.01.02", "CBIDlyStmtReqLogMsg");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.trim.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     * 
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link CBICashAccountType2 }
     * 
     */
    public CBICashAccountType2 createCBICashAccountType2() {
        return new CBICashAccountType2();
    }

    /**
     * Create an instance of {@link NameAndAddress10 }
     * 
     */
    public NameAndAddress10 createNameAndAddress10() {
        return new NameAndAddress10();
    }

    /**
     * Create an instance of {@link DateAndDateTimeChoice }
     * 
     */
    public DateAndDateTimeChoice createDateAndDateTimeChoice() {
        return new DateAndDateTimeChoice();
    }

    /**
     * Create an instance of {@link DateTimePeriodDetails }
     * 
     */
    public DateTimePeriodDetails createDateTimePeriodDetails() {
        return new DateTimePeriodDetails();
    }

    /**
     * Create an instance of {@link CBIBalanceType5Choice }
     * 
     */
    public CBIBalanceType5Choice createCBIBalanceType5Choice() {
        return new CBIBalanceType5Choice();
    }

    /**
     * Create an instance of {@link CBIReportEntry21 }
     * 
     */
    public CBIReportEntry21 createCBIReportEntry21() {
        return new CBIReportEntry21();
    }

    /**
     * Create an instance of {@link OrganisationIdentification4 }
     * 
     */
    public OrganisationIdentification4 createOrganisationIdentification4() {
        return new OrganisationIdentification4();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     * 
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link BankTransactionCodeStructure4 }
     * 
     */
    public BankTransactionCodeStructure4 createBankTransactionCodeStructure4() {
        return new BankTransactionCodeStructure4();
    }

    /**
     * Create an instance of {@link MessageIdentification2 }
     * 
     */
    public MessageIdentification2 createMessageIdentification2() {
        return new MessageIdentification2();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link CurrencyAndAmountRange2 }
     * 
     */
    public CurrencyAndAmountRange2 createCurrencyAndAmountRange2() {
        return new CurrencyAndAmountRange2();
    }

    /**
     * Create an instance of {@link CBITransactionReferences2 }
     * 
     */
    public CBITransactionReferences2 createCBITransactionReferences2() {
        return new CBITransactionReferences2();
    }

    /**
     * Create an instance of {@link Party6Choice }
     * 
     */
    public Party6Choice createParty6Choice() {
        return new Party6Choice();
    }

    /**
     * Create an instance of {@link FinancialInstrumentQuantityChoice }
     * 
     */
    public FinancialInstrumentQuantityChoice createFinancialInstrumentQuantityChoice() {
        return new FinancialInstrumentQuantityChoice();
    }

    /**
     * Create an instance of {@link CBICashBalance3 }
     * 
     */
    public CBICashBalance3 createCBICashBalance3() {
        return new CBICashBalance3();
    }

    /**
     * Create an instance of {@link CBIAccountStatement21 }
     * 
     */
    public CBIAccountStatement21 createCBIAccountStatement21() {
        return new CBIAccountStatement21();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification4 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification4 createBranchAndFinancialInstitutionIdentification4() {
        return new BranchAndFinancialInstitutionIdentification4();
    }

    /**
     * Create an instance of {@link PostalAddress6 }
     * 
     */
    public PostalAddress6 createPostalAddress6() {
        return new PostalAddress6();
    }

    /**
     * Create an instance of {@link CBIDlyStmtReqLogMsg000102 }
     * 
     */
    public CBIDlyStmtReqLogMsg000102 createCBIDlyStmtReqLogMsg000102() {
        return new CBIDlyStmtReqLogMsg000102();
    }

    /**
     * Create an instance of {@link CBIOrganisationIdentification4 }
     * 
     */
    public CBIOrganisationIdentification4 createCBIOrganisationIdentification4() {
        return new CBIOrganisationIdentification4();
    }

    /**
     * Create an instance of {@link CashBalanceAvailability2 }
     * 
     */
    public CashBalanceAvailability2 createCashBalanceAvailability2() {
        return new CashBalanceAvailability2();
    }

    /**
     * Create an instance of {@link CBIGenericOrganisationIdentification1 }
     * 
     */
    public CBIGenericOrganisationIdentification1 createCBIGenericOrganisationIdentification1() {
        return new CBIGenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link AlternateSecurityIdentification2 }
     * 
     */
    public AlternateSecurityIdentification2 createAlternateSecurityIdentification2() {
        return new AlternateSecurityIdentification2();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link DatePeriodDetails }
     * 
     */
    public DatePeriodDetails createDatePeriodDetails() {
        return new DatePeriodDetails();
    }

    /**
     * Create an instance of {@link ImpliedCurrencyAmountRangeChoice }
     * 
     */
    public ImpliedCurrencyAmountRangeChoice createImpliedCurrencyAmountRangeChoice() {
        return new ImpliedCurrencyAmountRangeChoice();
    }

    /**
     * Create an instance of {@link ProprietaryReference1 }
     * 
     */
    public ProprietaryReference1 createProprietaryReference1() {
        return new ProprietaryReference1();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice }
     * 
     */
    public AccountSchemeName1Choice createAccountSchemeName1Choice() {
        return new AccountSchemeName1Choice();
    }

    /**
     * Create an instance of {@link AmountRangeBoundary1 }
     * 
     */
    public AmountRangeBoundary1 createAmountRangeBoundary1() {
        return new AmountRangeBoundary1();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link ProprietaryParty2 }
     * 
     */
    public ProprietaryParty2 createProprietaryParty2() {
        return new ProprietaryParty2();
    }

    /**
     * Create an instance of {@link CashAccountType2 }
     * 
     */
    public CashAccountType2 createCashAccountType2() {
        return new CashAccountType2();
    }

    /**
     * Create an instance of {@link ContactDetails2 }
     * 
     */
    public ContactDetails2 createContactDetails2() {
        return new ContactDetails2();
    }

    /**
     * Create an instance of {@link NumberAndSumOfTransactions2 }
     * 
     */
    public NumberAndSumOfTransactions2 createNumberAndSumOfTransactions2() {
        return new NumberAndSumOfTransactions2();
    }

    /**
     * Create an instance of {@link ReturnReason5Choice }
     * 
     */
    public ReturnReason5Choice createReturnReason5Choice() {
        return new ReturnReason5Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     * 
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     * 
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link CashAccount16 }
     * 
     */
    public CashAccount16 createCashAccount16() {
        return new CashAccount16();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link CBIEntryTransaction2 }
     * 
     */
    public CBIEntryTransaction2 createCBIEntryTransaction2() {
        return new CBIEntryTransaction2();
    }

    /**
     * Create an instance of {@link CBIEntryDetails1 }
     * 
     */
    public CBIEntryDetails1 createCBIEntryDetails1() {
        return new CBIEntryDetails1();
    }

    /**
     * Create an instance of {@link ProprietaryAgent2 }
     * 
     */
    public ProprietaryAgent2 createProprietaryAgent2() {
        return new ProprietaryAgent2();
    }

    /**
     * Create an instance of {@link AmountAndCurrencyExchangeDetails4 }
     * 
     */
    public AmountAndCurrencyExchangeDetails4 createAmountAndCurrencyExchangeDetails4() {
        return new AmountAndCurrencyExchangeDetails4();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link BankTransactionCodeStructure6 }
     * 
     */
    public BankTransactionCodeStructure6 createBankTransactionCodeStructure6() {
        return new BankTransactionCodeStructure6();
    }

    /**
     * Create an instance of {@link BatchInformation2 }
     * 
     */
    public BatchInformation2 createBatchInformation2() {
        return new BatchInformation2();
    }

    /**
     * Create an instance of {@link AmountAndCurrencyExchange3 }
     * 
     */
    public AmountAndCurrencyExchange3 createAmountAndCurrencyExchange3() {
        return new AmountAndCurrencyExchange3();
    }

    /**
     * Create an instance of {@link RemittanceAmount1 }
     * 
     */
    public RemittanceAmount1 createRemittanceAmount1() {
        return new RemittanceAmount1();
    }

    /**
     * Create an instance of {@link CBIFinancialInstitutionIdentification7 }
     * 
     */
    public CBIFinancialInstitutionIdentification7 createCBIFinancialInstitutionIdentification7() {
        return new CBIFinancialInstitutionIdentification7();
    }

    /**
     * Create an instance of {@link BankTransactionCodeStructure5 }
     * 
     */
    public BankTransactionCodeStructure5 createBankTransactionCodeStructure5() {
        return new BankTransactionCodeStructure5();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link ProprietaryBankTransactionCodeStructure1 }
     * 
     */
    public ProprietaryBankTransactionCodeStructure1 createProprietaryBankTransactionCodeStructure1() {
        return new ProprietaryBankTransactionCodeStructure1();
    }

    /**
     * Create an instance of {@link BalanceSubType1Choice }
     * 
     */
    public BalanceSubType1Choice createBalanceSubType1Choice() {
        return new BalanceSubType1Choice();
    }

    /**
     * Create an instance of {@link CBITransactionParty2 }
     * 
     */
    public CBITransactionParty2 createCBITransactionParty2() {
        return new CBITransactionParty2();
    }

    /**
     * Create an instance of {@link CBIAccountIdentification4Choice }
     * 
     */
    public CBIAccountIdentification4Choice createCBIAccountIdentification4Choice() {
        return new CBIAccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link GenericIdentification3 }
     * 
     */
    public GenericIdentification3 createGenericIdentification3() {
        return new GenericIdentification3();
    }

    /**
     * Create an instance of {@link CashBalanceAvailabilityDate1 }
     * 
     */
    public CashBalanceAvailabilityDate1 createCashBalanceAvailabilityDate1() {
        return new CashBalanceAvailabilityDate1();
    }

    /**
     * Create an instance of {@link CreditLine2 }
     * 
     */
    public CreditLine2 createCreditLine2() {
        return new CreditLine2();
    }

    /**
     * Create an instance of {@link CBIGroupHeader42 }
     * 
     */
    public CBIGroupHeader42 createCBIGroupHeader42() {
        return new CBIGroupHeader42();
    }

    /**
     * Create an instance of {@link CBICashAccount20 }
     * 
     */
    public CBICashAccount20 createCBICashAccount20() {
        return new CBICashAccount20();
    }

    /**
     * Create an instance of {@link ReferredDocumentType1Choice }
     * 
     */
    public ReferredDocumentType1Choice createReferredDocumentType1Choice() {
        return new ReferredDocumentType1Choice();
    }

    /**
     * Create an instance of {@link CBIReturnReasonInformation10 }
     * 
     */
    public CBIReturnReasonInformation10 createCBIReturnReasonInformation10() {
        return new CBIReturnReasonInformation10();
    }

    /**
     * Create an instance of {@link CBIPartyIdentification321 }
     * 
     */
    public CBIPartyIdentification321 createCBIPartyIdentification321() {
        return new CBIPartyIdentification321();
    }

    /**
     * Create an instance of {@link PartyIdentification32 }
     * 
     */
    public PartyIdentification32 createPartyIdentification32() {
        return new PartyIdentification32();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation7 }
     * 
     */
    public StructuredRemittanceInformation7 createStructuredRemittanceInformation7() {
        return new StructuredRemittanceInformation7();
    }

    /**
     * Create an instance of {@link PersonIdentification5 }
     * 
     */
    public PersonIdentification5 createPersonIdentification5() {
        return new PersonIdentification5();
    }

    /**
     * Create an instance of {@link CBIBalanceType12 }
     * 
     */
    public CBIBalanceType12 createCBIBalanceType12() {
        return new CBIBalanceType12();
    }

    /**
     * Create an instance of {@link CurrencyExchange5 }
     * 
     */
    public CurrencyExchange5 createCurrencyExchange5() {
        return new CurrencyExchange5();
    }

    /**
     * Create an instance of {@link ProprietaryDate2 }
     * 
     */
    public ProprietaryDate2 createProprietaryDate2() {
        return new ProprietaryDate2();
    }

    /**
     * Create an instance of {@link DocumentAdjustment1 }
     * 
     */
    public DocumentAdjustment1 createDocumentAdjustment1() {
        return new DocumentAdjustment1();
    }

    /**
     * Create an instance of {@link AmountAndCurrencyExchangeDetails3 }
     * 
     */
    public AmountAndCurrencyExchangeDetails3 createAmountAndCurrencyExchangeDetails3() {
        return new AmountAndCurrencyExchangeDetails3();
    }

    /**
     * Create an instance of {@link CBIClearingSystemMemberIdentification2 }
     * 
     */
    public CBIClearingSystemMemberIdentification2 createCBIClearingSystemMemberIdentification2() {
        return new CBIClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link CBIBranchAndFinancialInstitutionIdentification4 }
     * 
     */
    public CBIBranchAndFinancialInstitutionIdentification4 createCBIBranchAndFinancialInstitutionIdentification4() {
        return new CBIBranchAndFinancialInstitutionIdentification4();
    }

    /**
     * Create an instance of {@link TechnicalInputChannel1Choice }
     * 
     */
    public TechnicalInputChannel1Choice createTechnicalInputChannel1Choice() {
        return new TechnicalInputChannel1Choice();
    }

    /**
     * Create an instance of {@link BranchData2 }
     * 
     */
    public BranchData2 createBranchData2() {
        return new BranchData2();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     * 
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link CBIRemittanceInformation5 }
     * 
     */
    public CBIRemittanceInformation5 createCBIRemittanceInformation5() {
        return new CBIRemittanceInformation5();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation3 }
     * 
     */
    public ReferredDocumentInformation3 createReferredDocumentInformation3() {
        return new ReferredDocumentInformation3();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link CBITransactionAgents2 }
     * 
     */
    public CBITransactionAgents2 createCBITransactionAgents2() {
        return new CBITransactionAgents2();
    }

    /**
     * Create an instance of {@link FromToAmountRange }
     * 
     */
    public FromToAmountRange createFromToAmountRange() {
        return new FromToAmountRange();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link ReferredDocumentType2 }
     * 
     */
    public ReferredDocumentType2 createReferredDocumentType2() {
        return new ReferredDocumentType2();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification7 }
     * 
     */
    public FinancialInstitutionIdentification7 createFinancialInstitutionIdentification7() {
        return new FinancialInstitutionIdentification7();
    }

    /**
     * Create an instance of {@link CBIAmountAndCurrencyExchange3 }
     * 
     */
    public CBIAmountAndCurrencyExchange3 createCBIAmountAndCurrencyExchange3() {
        return new CBIAmountAndCurrencyExchange3();
    }

    /**
     * Create an instance of {@link CBIParty6Choice }
     * 
     */
    public CBIParty6Choice createCBIParty6Choice() {
        return new CBIParty6Choice();
    }

    /**
     * Create an instance of {@link CBIRecipientIdentifier }
     * 
     */
    public CBIRecipientIdentifier createCBIRecipientIdentifier() {
        return new CBIRecipientIdentifier();
    }

    /**
     * Create an instance of {@link CBITotalTransactions2 }
     * 
     */
    public CBITotalTransactions2 createCBITotalTransactions2() {
        return new CBITotalTransactions2();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CBIDlyStmtReqLogMsg000102 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:CBI:xsd:CBIDlyStmtReqLogMsg.00.01.02", name = "CBIDlyStmtReqLogMsg")
    public JAXBElement<CBIDlyStmtReqLogMsg000102> createCBIDlyStmtReqLogMsg(CBIDlyStmtReqLogMsg000102 value) {
        return new JAXBElement<CBIDlyStmtReqLogMsg000102>(_CBIDlyStmtReqLogMsg_QNAME, CBIDlyStmtReqLogMsg000102 .class, null, value);
    }

}
